MODGO_MODULES =	\
	github.com/cheekybits/is	 v0.0.0-20150225183255-68e9c0620927 \
	github.com/djherbis/atime	 v1.1.0 \
	github.com/dustin/go-humanize	 v1.0.1 \
	github.com/fsnotify/fsnotify	 v1.7.0 \
	github.com/matryer/try		 v0.0.0-20161228173917-9ac251b645a2 \
	github.com/tdewolff/argp	 v0.0.0-20231129210956-bb03d6873d97 \
	github.com/tdewolff/parse/v2	 v2.7.7 \
	github.com/tdewolff/test	 v1.0.11-0.20231101010635-f1265d231d52 \
	golang.org/x/sys		 v0.15.0

MODGO_MODFILES =	\
	github.com/tdewolff/test	 v1.0.6 \
	golang.org/x/sys		 v0.4.0

