MODGO_MODULES =	\
	filippo.io/edwards25519		 v1.1.0 \
	github.com/cheekybits/is	 v0.0.0-20150225183255-68e9c0620927 \
	github.com/djherbis/atime	 v1.1.0 \
	github.com/fsnotify/fsnotify	 v1.8.0 \
	github.com/go-sql-driver/mysql	 v1.8.1 \
	github.com/jmoiron/sqlx		 v1.4.0 \
	github.com/lib/pq		 v1.10.9 \
	github.com/matryer/try		 v0.0.0-20161228173917-9ac251b645a2 \
	github.com/mattn/go-sqlite3	 v1.14.22 \
	github.com/pelletier/go-toml	 v1.9.5 \
	github.com/tdewolff/argp	 v0.0.0-20240625173203-87b04d5d3e52 \
	github.com/tdewolff/parse/v2	 v2.7.19 \
	github.com/tdewolff/test	 v1.0.11-0.20240106005702-7de5f7df4739 \
	golang.org/x/sys		 v0.25.0

MODGO_MODFILES =	\
	github.com/go-sql-driver/mysql	 v1.6.0 \
	github.com/go-sql-driver/mysql	 v1.7.1 \
	github.com/jmoiron/sqlx		 v1.3.5 \
	github.com/lib/pq		 v1.2.0 \
	github.com/mattn/go-sqlite3	 v1.14.6 \
	github.com/tdewolff/test	 v1.0.11-0.20231101010635-f1265d231d52 \
	github.com/tdewolff/test	 v1.0.6 \
	golang.org/x/sys		 v0.13.0

