COMMENT =	modern shadowsocks in Go

MODGO_MODNAME =	github.com/shadowsocks/go-shadowsocks2
MODGO_VERSION =	v0.1.5

DISTNAME =	go-shadowsocks2-${MODGO_VERSION}

CATEGORIES =	net

HOMEPAGE =	https://github.com/shadowsocks/go-shadowsocks2/

MAINTAINER =	Igor Zornik <mocheryl@mocheryl.org>

# apache 2.0
PERMIT_PACKAGE =	Yes

WANTLIB +=	c pthread

MODULES =	lang/go

.include "modules.inc"

.include <bsd.port.mk>
